### ISSUE TITLE
Carriers: TextMap*Adapter (Java) vs DictionaryCarrier (C#)

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#24]
After reading through https://github.com/opentracing/opentracing-java/issues/31 for about 5 times, I think I finally understand all statements and I agree with the current Tracer API. C# already has the same signature on `ITracer` so we should be good here. However, we currently do something else differently in C#.

Java uses two separate classes for representing a regular map/dictionary:
```Java
public final class TextMapInjectAdapter implements TextMap {
    private final Map<String,String> map;

    public TextMapInjectAdapter(final Map<String,String> map) {
        this.map = map;
    }

    @Override
    public Iterator<Map.Entry<String, String>> iterator() {
        throw new UnsupportedOperationException("TextMapInjectAdapter should only be used with Tracer.inject()");
    }

    @Override
    public void put(String key, String value) {
        this.map.put(key, value);
    }
}

public final class TextMapExtractAdapter implements TextMap {
    private final Map<String,String> map;

    public TextMapExtractAdapter(final Map<String,String> map) {
        this.map = map;
    }

    @Override
    public Iterator<Map.Entry<String, String>> iterator() {
        return map.entrySet().iterator();
    }

    @Override
    public void put(String key, String value) {
        throw new UnsupportedOperationException("TextMapInjectAdapter should only be used with Tracer.extract()");
    }
}
```

In C# we currently have just one type that handles both cases:
```csharp
public class DictionaryCarrier : ITextMap
{
    private readonly IDictionary<string, string> _payload;

    public DictionaryCarrier(IDictionary<string, string> payload)
    {
        _payload = payload;
    }

    public IEnumerable<KeyValuePair<string, string>> GetEntries()
    {
        return _payload;
    }

    public string Get(string key)
    {
        string value;
        return _payload.TryGetValue(key, out value) ? value : null;
    }

    public void Add(string key, string value)
    {
        _payload[key] = value;
    }
}
```

*What's the advantage of using two separate classes for this?*

Since both classes could be used for Inject/Extract it seems like it's pretty easy for users to mess this up and get runtime exceptions. 
Trace implementations have to support inject & extract for TEXT_MAP so there isn't a case where it would support just one version, right?

/cc @bensigelman @dawallin @yurishkuro

**Comment by yurishkuro** [comment]
> After reading through opentracing/opentracing-java#31 for about 5 times

so the reason things are a bit messy in Java is because you may have noticed during those 5 reads :-) that my original proposal for format was `Format<R, W>` and the method signatures were 
```
inject(SpanContext, Format<?, W>, W carrier)
extract(Format<R, ?>, R carrier)
```
where `?` stands for "don't care, I'm only restricting the _other_ type".

The intention was to allow the carrier type to be asymmetrical for read and write operations, e.g. in Go we have TextMapReader and TextMapWriter interfaces instead of a single TextMap. IMO that would've been a much cleaner design. In contrast, when you have a single TextMap interface, the implementation that's wrapping something else has to either implement both directions of data flow, or be separated into two implementations as you've discovered. Problem with implementing both directions is that the carrier is usually a wrapper around some other data structure, like RPC Headers object, and depending on the context that underlying object may R or W but not both. E.g. in a server handler, you may be given headers as a Map, but it could be an immutable map that will throw exception if you try to write to it. So your adapter of that map into TextMap carrier is going to implement a write operation that is guaranteed to fail.

Why the dual-type Format did not take in Java - you'd have to read the thread. In a democracy you often end up with compromises. In Go the generics don't exist so we could not implement strong typing, but we could define the convention for carrier types, and that convention is based on dual R/W types for both text map and binary formats.

Someone mentioned earlier that in C# the `<?>` approach doesn't work (which is a bit surprising since it's the basic mechanism for covariance), and since things are moving towards singly-typed Formats I'd say your DictionaryCarrier is fine. I, in fact, also got burnt once by the duality in Java TextMap wrappers, since the wrong carrier does not get caught by the type system (as it would've been with dual R/W typed Formats).

**Comment by cwe1ss** [comment]
thanks for your feedback, Yuri! I'll keep the current code then - if anyone has further comments/concerns feel free to open another issue.

@yurishkuro:
> Someone mentioned earlier that in C# the <?> approach doesn't work (which is a bit surprising since it's the basic mechanism for covariance)

In C#, `in` and `out` keywords can be used to declare [contra-/covariance rules on generics](https://msdn.microsoft.com/en-us/library/dd799517(v=vs.110).aspx) but to be honest, I don't know much about this topic. AFAIK it's not possible to keep a type constraint undefined in a concrete implementation. That's why it wasn't possible to have different `LogField<T>` types in a list (which we briefly tried in the logging topic).
