### ISSUE TITLE
AbstractTracer and BasicTracer packages

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#31]
I now have a first version of [base classes for tracers](https://github.com/cwe1ss/opentracing-contrib-dotnet/tree/master/src/OpenTracing.Tracer.Abstractions) in my contrib project. These are very similar to the [AbstractTracer package](https://github.com/opentracing/opentracing-java/tree/master/opentracing-impl/src/main/java/io/opentracing/impl) in Java.

It would make sense to also use these base classes in our BasicTracer. However, this brings up the question in which repository these base classes should be.

Should they stay in the contrib-repo (which has yet to be moved to the opentracing-contrib org) and BasicTracer should take a dependency on it? This might seem a little weird because now a project from the "official" org would take a dependency on a "contrib" project.

Or should the package be "made official" by moving it directly into the `opentracing-csharp` repo - like in Java?

Your thoughts?

**Comment by bensigelman** [comment]
@cwe1ss sorry for the insane delay here – I apparently need a better way to manage notifications across the numerous git repos I care about these days :(

There's a third option which I would probably be supportive of: namely, to move the various BasicTracer impls into `opentracing-contrib` since they don't affect the APIs themselves. Thoughts?

**Comment by cwe1ss** [comment]
Outdated.
