### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by TerribleDev** [opentracing/opentracing-csharp#37]
Hello everyone, I recently went to monitorama, and I've been exploring tracing quite a bit lately. Some of our stuff will be hosted in dotnet core in the future. I'm hoping I can help get csharp a proper open tracing client, with rock solid docs. I'm willing to help make this happen. I'm wondering, what the status of this project is, what is the goals, and how can I help (if you even need help) to ensure those goals happen.

**Comment by bhs** [comment]
@TerribleDev thank you for reaching out about this!

@cwe1ss is the best person to coordinate with about OT+C#.

Off the top of my head, the most helpful things you could do would be one of...

1. Think hard about https://github.com/opentracing/opentracing-csharp/pull/36 and provide feedback, esp about C# best practices
1. Add github.com/opentracing-contrib integrations for popular C# frameworks and libraries
1. Add bindings from OT-C# to additional tracing systems (happy to provide suggestions if that's helpful)

Feel free to ping me or others on Gitter... that's probably an easier place to chat than github issues.

I'm going to close this since I don't know what would mark it as "resolved", but please don't misinterpret that as an unfriendly gesture – I'm happy to continue the discussion here or elsewhere.

**Comment by TerribleDev** [comment]
@bhs :+1: I'll probably start logging into gitter, and the github issues on a regular basis. Thanks for including me!
