### ISSUE TITLE
Is there a "NotNull" Tracer implementation?

### ISSUE THREAD

**Issue by Gildissimo** [opentracing/opentracing-csharp#41]
Is there a Official/Not Official Tracer implementation for .net? Any suggestion to implement a simple version of ITracer interface (e.g. using a ms sql server database or files) ?

**Comment by gideonkorir** [comment]
Checkout the code here: [opentracing-contrib](https://github.com/cwe1ss/opentracing-contrib-dotnet). No nuget package but looks good IMHO

**Comment by cwe1ss** [comment]
My linked opentracing-contrib project is currently in a "work in progress" state and I haven't done much testing with it yet. It definitely needs more work before it can be published on NuGet.

Unfortunately, I'm currently a bit demotivated because I'm still not sure how this library should coexist with the new [Activity](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md) type from System.Diagnostics.DiagnosticSource. It is similar to OpenTracing's `Span` but it also has some very important differences and missing features.

It would be great if more people were interested in this project and willing to help to discuss possible solutions.

**Comment by Gildissimo** [comment]
I could help you. Before I need a bit of time to understand well this library, then I could offer my contribution! Thanks for your contribution!

**Comment by gideonkorir** [comment]
@cwe1ss I'm also willing to help. I've been reading the code (The diagnostic adapter is really cool ) and actually got the samples to run + send traces to zipkin. We could move this to the contrib project and see how we could help

**Comment by Gildissimo** [comment]
@cwe1ss @gideonkorir I've compiling your sources using old VS2015 prjs (due to not compatible prj versions with 2017). If you need I could give you this versions as well

**Comment by Gildissimo** [comment]
@cwe1ss do you have the implementation for BackoffTimer and TickContext?

**Comment by cwe1ss** [comment]
If anyone is interested in getting a OpenTracing compatible Zipkin tracer, please have a look at https://github.com/openzipkin/zipkin4net/issues/191 ("Coordinating the creation/endorsement of a OpenTracing->Zipkin tracer").

**Comment by cwe1ss** [comment]
Another tracking issue for an upcoming C# Jaeger client: https://github.com/jaegertracing/jaeger/issues/578

**Comment by cwe1ss** [comment]
I'll close this as there's now an official repo for the C# Jaeger tracer: https://github.com/jaegertracing/jaeger-client-csharp
