### ISSUE TITLE
Parity with the other libraries

### ISSUE THREAD

**Issue by ndrwrbgs** [opentracing/opentracing-csharp#47]
The opentracing-csharp library seems to not get much love & attention lately. I was curious if there was interest in bringing it up to parity with more active/maintained opentracing-java, since the languages are similar enough that updating to or even porting the code would be trivial. Many concepts one may want are already there (such as those mentioned directly or indirectly by #36, #44, #35).

This question is obviously motivated by the assumption that given that the java implementation has a large user base, changes to it's exposed API may end up being more _practically speaking_ official than changes actually in the specifications. If, alternatively, it's desirable to keep this library _exactly_ matching the specs with nothing more, then that should be decided/noted explicitly, which would give guidance to the proper action with PRs like #36.

**Comment by cwe1ss** [comment]
Sorry for not replying - I’m on a sabbatical right now. Please see https://github.com/opentracing/opentracing-csharp/issues/52 for a topic that IMO should be resolved before we do any further changes.

**Comment by cwe1ss** [comment]
I'm back and I'll have at least a few days where I can work on OpenTracing. If you guys are ok with it, I'll create several PRs to bring this library up to date with the Java version. I'd rather not merge #50 as it is right now because it doesn't follow C# guidelines and it changes some things which I think should not be changed so I'd like to at least have them discussed briefly. But as I've said there, I'd be happy to wait for changes/other PRs/feedback from @ndrwrbgs as I haven't been active here so I don't want to make anyone unhappy :)

/cc @tedsuo @carlosalberto (I can't see if anyone else is a owner/contributor)

**Comment by cwe1ss** [comment]
No more need for this issue - the work to ensure parity is ongoing in #55 and several PRs.
