### ISSUE TITLE
Relation to .NET‘s Activity type 

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#52]
I think we should try to figure out if/how this project can/should coexist with the new .NET framework type `Activity`.

Please see https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md for some documentation. It’s very similar to OpenTracing but it has a few important differences.

The userbase for the C# OpenTracing implementation is very small (basically non-existent) so we should make sure people who are interested in this topic invest their time properly.

I really want proper feedback from multiple people before I invest any more time into this.

**Comment by gideonkorir** [comment]
@cwe1ss thanks for the feedback, I'll be doing my homework

**Comment by ndrwrbgs** [comment]
My concern with this has been since I read your initial interactions with the dotnet team. Unfortunately, from viewing them it looked like you weren’t able to get much traction in providing feedback or direction - and that concerns me as far as “putting all my eggs in that basket”.

OpenTracing wants to be a cross language standard, so I feel like the only way for it to coexist with Activity would be for Activity to implement OpenTracing (by nature, since OpenTracing is cross language it’s more general than Activity can ever be).

I’d personally want to use OpenTracing APIs and, if so chosen, use Activity propagation as _an implementation_ of it, easy to swap out to something else as needed. It would benefit from the very active OpenTracing community at large rather than a few individuals at Microsoft and would provide the ability for folks from other languages to use .NET tracing in familiar semantics.


I guess for me the only way I’d prefer to use something specific for the language was if it were
1. _so well_ designed that it far surpassed the open source option
2. It had special compiler/runtime mechanisms that made it work much better than the OSS solution (well, if using it as an interface implementation somehow lost those benefits)

Obviously duplicating work at large is a **major** negative, but in my experience the community at large ends up benefiting from new ideas/improvements _any_ language gets rather than living in isolation.

**Comment by ndrwrbgs** [comment]
Regarding the user base, I believe a major reason for this may be that there isn’t an implementation today, at least officially sanctioned.
It helps that dotnet is open source now and the community is finally starting to move towards that ideology like java (enterprise companies like Microsoft who use the language are becoming more open to consuming and contributing to OSS) but I personally think that open source in dotnet is still in its early ages (I think that’s possibly even self-evident here in the recent interest in a fundamental like a tracing library).

**Comment by TerribleDev** [comment]
@ndrwrbgs To say the .net community hasn't been doing open source until recently, is a pretty harsh statement given that there are .net projects like wix toolset which have been around since 2004, or nhibernate which has been around since '08. 

There are plenty of companies running non-dotnet stacks that are just as adverse to not pulling down open source code.

I suspect you will find that developers whom don't work on .net believe its still tied to windows in one form or another, and that is a huge put off. I would assert that its more of an external marketing problem at this point, and not an endemic issue with the dotnet community as a whole.

**Comment by TerribleDev** [comment]
@cwe1ss Personally, I don't think it makes sense to use the Activity type. At the end of the day, the .net team is going to provide solutions that benefit themselves, and other microsoft products such as Application Insights. 

Also since this is meant to be cross language, and all communication both incoming, and outgoing should use the same interface, it only makes sense to come up with opentracing contracts in .net, and not System.Diagnostics.Activity contracts.

As much as I like that you are trying to consider all angles, I do agree with @ndrwrbgs that

**Comment by ndrwrbgs** [comment]
@TerribleDev hope I wasn't misunderstood; I definitely did not say the .net community hasn't done open source until recently anywhere there :smile:, nor would I ever! That statement is definitely not true.

Your second post's second paragraph is in line with my opinions.

**Comment by bmermet** [comment]
Adding my two cents to the discussion. I don't think that `Activity` is pursuing the same goal as the OpenTracing standard.

OpenTracing aims first at providing a set of standardized interfaces that can then be implemented by different vendors with the goal to make it very easy for an application to switch from one vendor to another. The choice of defining only interfaces, leaves a lot of flexibility to each vendors implementation.

`Activity` on the other end is an opinionated tracing implementation that as far I can tell doesn't provide many extensibility points. It forces you to use its own id generation mechanism, which makes it difficult to inter operate with exisiting systems. It doesn't have abstractions for cross-process propagation. And while its automatic in process context propagation mechanism based on `AsyncLocal`/`CallContext` might be relevant for the majority of use cases it doesn't let you plug your own implementation or manually set parent/children relations between your activities.

I think the OpenTracing approach of a standard based on interfaces and not on a concrete implementation is way more flexible and extensible and should be the way to go. Not to say that I agree that IMO it makes more sense to rely on a standard defined by the OpenTracing community and consistent with other languages apis.

**Comment by Aaronontheweb** [comment]
As someone working on consuming this package inside a large framework at the moment, let me be unambiguous: the `Activity` type is going to be yet another not-invented-here MSFT standard that no one outside of a handful of die-hard Microsoft Solutions Consulting customers ever end up adopting at scale. 

One day it may have buy-in in the form of back-end tooling for visualization, but it doesn't. Debating whether or not we should halt the development of this standard and this project in favor of consuming the `Activity` type would be like the jQuery folks deciding not to pursue their implementation because Microsoft was developing ASP.NET WebControls. 

Microsoft doesn't have any mindshare, tooling, or history in this space. There are dozens upon dozens of Zipkin client implementations in C# already - the demand for OpenTracing and its implementations has already made `Activity` irrelevant. 

So IMHO, close this issue and let's move onto updating this package and unblock the project. If `Activity` ever does get any traction in the future, we can revisit later. Don't stop the work in the meantime.

**Comment by tedsuo** [comment]
Thanks @Aaronontheweb. Now that Java 0.31 has landed we are going to revisit this API.

**Comment by Aaronontheweb** [comment]
@tedsuo great! I have some PRs I'd like to send over the next couple of weeks. Looking forward to seeing our end-users adopt this standard and the clients which implement it.

**Comment by ndrwrbgs** [comment]
FYI #50 exists :) It had to wait until January per the December sync call, but now it's January so whenever folks have a chance to look :) (but it's based on 0.30 I believe)

**Comment by cwe1ss** [comment]
Even though we are now working on the next version, I'd like to keep this issue open for now to raise further awareness and to comment on a few things discussed here.

While I agree with most of your views in principal, I think you're also missing an important point: 

It's not a question about whether there will be OpenTracing OR `Activity`. `Activity` is a part of the .NET framework and __it is already used for instrumenting the most important libraries/frameworks in the latest .NET stack__: HttpClient calls, SqlClient calls, ASP.NET Core requests, EntityFrameworkCore calls.

This also means that __implementations MUST use `Activity`__ as this is the best way to hook into these scenarios. You could have e.g. your own HttpClientHandler but that's just not as user-friendly as having an automatic hook that doesn't require application developers to register custom OT handlers etc. I think in the case of Sql-calls using DiagnosticSource/Activity is even the only way to place a hook.

Of course, instead of forcing all implementations to subscribe to Activities directly, we can build one "Activity -> OpenTracing"-bridge but this obviously has a performance/memory impact as many tracing systems will have to do yet another transformation into their own data structures.

Obviously, all of Microsoft (e.g. Azure SDKs) will eventually implement Activity and not OpenTracing. This means that in the OSS world OpenTracing instrumentation code will only be used by a few non-MS libraries (hopefully gRPC, ...). And even here one has to wonder why a library developer should implement OpenTracing directly instead of Activity as Activity will always have a bigger support by tracing implementations (since they MUST support it directly or indirectly).

This brings us to corporate development. While the same choices apply for internal libraries and OT might be valuable here, for applications/microservices we also have upcoming stuff like OpenCensus that might provide more value than using OpenTracing alone as it (AFAIU) guarantees vendor-independence, multiple outputs, a better local development experience with its local agent and it can easily have its own `Activity`/OT-subscription so it's like a superset of everything.

Of course, there's neither good .NET OpenTracing implementations nor is there a .NET OpenCensus version so we don't know yet what this story will look like. 

I'm very passionate about this topic and I like OpenTracing (otherwise I wouldn't be here) but I also want to make sure we are investing our time properly to actually make an impact towards a better distributed tracing story in .NET. And this requires as much feedback and opinions as possible and also that more people learn about `Activity` as it is here to stay - no matter if one likes it or not.

**Comment by carlosalberto** [comment]
> Of course, instead of forcing all implementations to subscribe to Activities directly, we can build one "Activity -> OpenTracing"-bridge but this obviously has a performance/memory impact as many tracing systems will have to do yet another transformation into their own data structures.

This is something that I was thinking about. Sure, not perfect, but that would be better than nothing (because, as you mentioned, it's already well adopted within the base class library itself).

When it comes to the invested time, I see users willing to contribute and willing to try out anyway, so I *feel* we should channel that now (while keeping things small and curated, while we find out how the future for Tracing under C# looks ;) )

**Comment by cwe1ss** [comment]
I'm going to close this as there's been no new comments.

PS: My [OpenTracing.Contrib.NetCore](https://github.com/opentracing-contrib/csharp-netcore) project is a big DiagnosticSource/Activity -> OpenTracing bridge.
