### ISSUE TITLE
Target netstandard1.3 and net45

### ISSUE THREAD

**Issue by cwe1ss** [opentracing/opentracing-csharp#62]
I'd like to make sure people don't do weird stuff with this library unless we know about it. One way to ensure this is to only target officially supported versions of .NET Core and the full .NET framework.

We currently target netstandard1.0 but this also includes stuff like Silverlight and Windows Phone, which are no longer supported by Microsoft.

For this reason, I'd like to target `netstandard1.3` (which supports .NET Core 1+, .NET 4.6+, Xamarin, Mono, UWP) and `net452` to support .NET 4.5.2 (which is the only officially supported .NET 4.5 version)

See [.NET Standard](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) for details.

If people really need it for older platforms, we can always talk about it and loosen this requirement - it's always easier to add older targets than to remove them.

Edit 2018-02-20: We are using `net45` instead of `net452` (see comments)

**Comment by cwe1ss** [comment]
@bmermet @ndrwrbgs you've said in #51 that you're targeting .NET 4.5 at work. Are you targeting .NET 4.5.2 or an older version? (Note that older versions are no longer supported by Microsoft)

**Comment by cwe1ss** [comment]
I've committed this change with #63. Feel free to comment here if that's a problem... we can easily change that.

**Comment by MikeGoldsmith** [comment]
I think we should target net45 too. It's still listed as part of the compatibility matrix on the MS documentation pages and because we fall back to CallContext when using < net462 (AsyncLocal not available) we're still covered.

I would also require it as part of my integration with Couchbase SDK as we currently target net45, netstandard1.3 and netstandard2.0. As an integration library, we're not in control of what framework version our customers use.

**Comment by cwe1ss** [comment]
I changed it to `net45` instead of `net452`.

**Comment by cwe1ss** [comment]
I've just released v0.11.0. Please create a new issue with your scenario if you need support for lower .NET Standard versions.
