### ISSUE TITLE
Field class?

### ISSUE THREAD

**Issue by grounded042** [opentracing/opentracing-csharp#69]
In the go OpenTracing library they have a concrete log `Field` class (https://github.com/opentracing/opentracing-go/blob/master/log/field.go). Is there any desire / thought to have a `Field` class in this lib or is the thought to leave that up to the actual implementation that uses this library? I know the Java lib does not have the `Field` class - just the standard log fields like this lib does.

Also kind of interesting is that the go lib does not define the standard log fields - I'm guessing they leave that up to the end user to actually log those keys.

**Comment by cwe1ss** [comment]
Hi, the current goal is to get a release ASAP that's as close to Java as possible. This should ensure that everyone's unblocked from using the API. 

After that, we surely can think about this and discuss it with the Java folks.

**Comment by grounded042** [comment]
Good point on getting something workable ASAP. Definitely makes sense to put off anything along the lines of an extra feature add for the time being.

**Comment by cwe1ss** [comment]
I've been looking at the Go code and I do not really see the use case for this in C#. How would this be used (some C# pseudo/demo code would be great) and what's the advantage over the current solution?

**Comment by grounded042** [comment]
The specific example I'm thinking of is I have a `Field` and `Field<T>` class in [LetsTrace](https://github.com/Chatham/LetsTrace/blob/master/src/LetsTrace/Field.cs). When I want to send data to a system like Jaeger which supports specific types I can use the Field class and easily [use a switch to map the types to what Jaeger wants](https://github.com/Chatham/LetsTrace.Jaeger/blob/master/src/LetsTrace.Jaeger/Transport/JaegerFieldExtensions.cs).

I could just do a bunch of `if (logField is int intLogField) { }`, but I'm not a big fan of a bunch of if else statements. 

I guess what I'm thinking of is that having a Field that supports generic types allows implementations to hook into the Field and handle types different ways more easily than with `object`.

**Comment by cwe1ss** [comment]
You can [switch on everything](https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching#using-pattern-matching-switch-statements) with the new pattern matching features in C#. 

My main concern here is performance/memory pressure. Wrapping every log field in a type seems like a lot of overhead.

**Comment by ndrwrbgs** [comment]
I also dislike having a `IDictionary<string, object>` for Log for a couple reasons
1. Not as descriptive as specifying the types
1. Common types like value-types will have to be boxed
1. Handling code will likely _usually_ have to check the types

The problems with avoiding it though are...
1. C# doesn't have a kind of `IDictionary<string, Field<?>>`, so it'd have to take either a `Field` that did not expose the `Value` (since it doesn't know the type) or it'd have to take a `Field<object>`, which gets us back to the start
1. Having **strongly** typed would require introducing methods for various types like the `SetTag` methods, but this would mean when trying to log 3 fields (say, HttpStatusCode, HttpMessage, HttpUrl), you'd have to call potentially 3 different log messages.
   1. This may actually be good performance wise and type safety wise, but it does mean that if the `ITracer` wants to batch these to log them all as one message that's no longer possible.

I guess it'd be easiest to talk about this though with an example of what is being proposed?

**Comment by grounded042** [comment]
@cwe1ss nice, I did not know about switching on everything. I had specifically looked into that and saw an old post saying you could not switch on type.

@ndrwrbgs in my example I use an abstract class so I can do `IDictionary<string, Field>` and pass in a `Field<T>` to it. But yeah, we still have some fun getting the type. 

I really like that we can switch on an object type though - that was one of my main arguments for having a Field class, but now I don't know that I want one anymore.

The one thing that is still tripping me up is what happens when you log a type you're not sure what to do with? So you can switch on the type which makes it pretty easy to handle built-in types. But what about, for example, Exceptions? Since a log is an object you can pass in any exception. Do I need a special case for each type of exception? That gets pretty exhaustive and one could even argue that people shouldn't be passing in a bunch of different exceptions to tracing. But, we've allowed that via `object`. We can just support the basic types and then fall through to `.ToString()` as the default on all the rest, but that might not give the details we want. Is that on the person using the tracing implementation to actually take care of making sure that if they log a non-built-in type they are either happy with what `.ToString()` produces or they explicitly log what they want individually? Granted even if you had a generic field you will probably run into the same issue.

**Comment by ndrwrbgs** [comment]
I would agree with this, that since `Tag` has official and supported types, I'd argue that `Log` should also have a whitelist of types.

That said, I would have to defer to the https://github.com/opentracing/specification folks for why it accepts object (I think `Exception` is part of that reason, but that can be whitelisted also - perhaps there's a reason based in other languages)

**Comment by grounded042** [comment]
Looking at the go library it's almost as if they decided to only handle certain types and if you log an unsupported type, bummer. Granted in our example of `Exception`, the go `error` is pretty much the only type instead of the plethora of `Exception` types in C#.

I think in this libs case it was leaving the actual handling of certain types up to the implementation and not the API

**Comment by cwe1ss** [comment]
> @grounded042: But what about, for example, Exceptions? Since a log is an object you can pass in any exception. Do I need a special case for each type of exception?

I *think* that you can just use `case Exception ex:` and every derived type will match that case. I haven't tried this though.

I also think that this issue is "too impactful" to be discussed here in the csharp repo. This would be a huge deviation that doesn't have a C#-language specific reason. I'd therefore suggest you propose this in [opentracing-java](https://github.com/opentracing/opentracing-java) where we have a bigger audience and can decide together about whether or not this is something that should be done.

**Comment by grounded042** [comment]
Cool. Thanks @cwe1ss.
